const consonantMappings: Map<string, string | string[]> = new Map();
consonantMappings.set("b", "b");
consonantMappings.set("tʃ", "ch");
consonantMappings.set("d", "d");
consonantMappings.set("ð", "dh");
consonantMappings.set("f", "f");
consonantMappings.set("ɡ", ["g", "gh"]);
consonantMappings.set("h", "h");
consonantMappings.set("dʒ", "j");
consonantMappings.set("k", "k");
consonantMappings.set("x", "kh");
consonantMappings.set("l", "l");
consonantMappings.set("m", "m");
consonantMappings.set("n", "n");
consonantMappings.set("ŋ", "ng");
consonantMappings.set("ŋk", "nk");
consonantMappings.set("p", "p");
consonantMappings.set("r", "r");
consonantMappings.set("s", ["s", "ss"]);
consonantMappings.set("ʃ", "sh");
consonantMappings.set("t", "t");
consonantMappings.set("tʃ", "tch");
consonantMappings.set("θ", "th");
consonantMappings.set("v", "v");
consonantMappings.set("w", "w");
consonantMappings.set("hw", "wh");
consonantMappings.set("j", "y");
consonantMappings.set("z", "z");
consonantMappings.set("ʒ", "zh");

const vowelMappings: Map<string, string | string[]> = new Map();
vowelMappings.set("æ", "a");
vowelMappings.set("ɑː", "ah");
vowelMappings.set("ɛər", "air");
vowelMappings.set("ɑːr", "ar");
vowelMappings.set("ær", "arr");
vowelMappings.set("ɔː", "aw");
vowelMappings.set("eɪ", "ay");
vowelMappings.set("ɛ", ["e", "eh"]);
vowelMappings.set("iː", "ee");
vowelMappings.set("i", "ee");
vowelMappings.set("ɪər", "eer");
vowelMappings.set("ɛr", "err");
vowelMappings.set("juː", "ew");
vowelMappings.set("aɪ", ["eye", "y"]);
vowelMappings.set("ɪ", ["i", "ih"]);
vowelMappings.set("aɪər", "ire");
vowelMappings.set("ɪr", "irr");
vowelMappings.set("ɒ", "o");
vowelMappings.set("oʊ", "oh");
vowelMappings.set("ɔɪər", "oir");
vowelMappings.set("uː", "oo");
vowelMappings.set("u", "oo");
vowelMappings.set("ʊər", "oor");
vowelMappings.set("ɔːr", "or");
vowelMappings.set("ɒr", "orr");
vowelMappings.set("aʊər", "our");
vowelMappings.set("aʊ", "ow");
vowelMappings.set("ɔɪ", "oy");
vowelMappings.set("ʌ", ["u", "uh"]);
vowelMappings.set("ɜːr", "ur");
vowelMappings.set("jʊər", "ure");
vowelMappings.set("ʌr", "urr");
vowelMappings.set("ʊ", "uu");
vowelMappings.set("ʊr", "uurr");
vowelMappings.set("ə", "uh");
vowelMappings.set("ər", "er");

export const mappings: Map<string, string | string[]> = new Map([...consonantMappings, ...vowelMappings]);

export const STRESS_MARK = "ˈ";
export const SECONDARY_STRESS_MARK = "ˌ";

export const consonants = [...consonantMappings.keys()];
export const vowels = [...vowelMappings.keys()];

// miscellaneous
export const acceptedSymbols = ["/", "[", "]", " "];

export const validChunks = [...consonants, ...vowels, STRESS_MARK, SECONDARY_STRESS_MARK, ...acceptedSymbols];
