name: 'Deploy to gh-pages'
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: 'Build and Deploy'
    runs-on: 'ubuntu-latest'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout code'
<<<<<<< Updated upstream
        uses: 'actions/checkout@v6'
      - name: 'Install Node.js'
        uses: 'actions/setup-node@v6'
=======
        uses: 'actions/checkout@v5'
      - name: 'Install Bun'
        uses: 'oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6'
>>>>>>> Stashed changes
        with:
          bun-version: 'latest'
      - name: 'Install Bun packages'
        run: 'bun install --frozen-lockfile'
      - name: 'Build project'
        run: 'bun run build'
      - name: 'Deploy'
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          bun run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: "${{ secrets.ACCESS_TOKEN }}"
          repository: "${{ github.repository }}"
