name: 'ESLint'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    name: 'ESLint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Install Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22.x'
      - name: 'Install NPM packages'
        run: 'npm ci'
      - name: 'Run ESLint'
        run: 'npm run lint'
