name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v7'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64'
        with:
          generate_release_notes: true
