name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v6'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe'
        with:
          generate_release_notes: true
