name: 'Vitest'
on:
  pull_request:
    branches: ['main']
jobs:
  vitest:
    runs-on: 'ubuntu-latest'
    permissions:
      # Required to checkout the code
      contents: 'read'
      # Required to put a comment into the pull-request
      pull-requests: 'write'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v5'
      - name: 'Install Node.js'
        uses: 'actions/setup-node@v5'
        with:
          node-version: '22.x'
      - name: 'Install NPM packages'
        run: 'npm ci'
      - name: 'Test'
        run: 'npm run test'
