name: 'Vitest'
on:
  pull_request:
    branches: ['main']
jobs:
  vitest:
    runs-on: 'ubuntu-latest'
    permissions:
      # Required to checkout the code
      contents: 'read'
      # Required to put a comment into the pull-request
      pull-requests: 'write'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v6'
      - name: 'Install Bun'
        uses: 'oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6'
        with:
          bun-version: 'latest'
      - name: 'Install Bun packages'
        run: 'bun install --frozen-lockfile'
      - name: 'Test'
        run: 'bun run test'
